name: Build and Deploy
on: 
  push:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: deploy.yml
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.7' 
      - name: Install Dependencies
        run: |
          pip install -r ./requirements.txt
      - name: Build
        run: |
          python ./main.py
        env:
          PYTHONUNBUFFERED: 1
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GIT_CONFIG_NAME: covidtracker
          GIT_CONFIG_EMAIL: russ+covidtracker@garrett.co.uk
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: output
